server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.127.130:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.127.130:3306/lay?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: '*'
