server:
  port: 8002

spring:
  application:
    name: cloud-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.127.129:3306/lay?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456