server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.127.130:8848
        group: "SEATA_GROUP"
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.127.130:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.127.130:8848
      group: "SEATA_GROUP"
      namespace: "public"
      username: "nacos"
      password: "nacos"

logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:mapper/*.xml
